### ISSUE TITLE
Not valid type suggestion when using library that use another library

### ISSUE THREAD

**Issue by jisoldi** [mulesoft-labs/raml-suggestions#11]
The problem is reported in an issue in the api-designer, but the suggestion is generated in this module. This is the issue: https://github.com/mulesoft/api-designer/issues/433#issuecomment-249110274

**Comment by ddenisenko** [comment]
Reproducible, completion does suggest types, which are out of scope.

**Comment by dreamflyer** [comment]
will be published in v0.0.19.
