### ISSUE TITLE
The following line to an example has no suggestions

### ISSUE THREAD

**Issue by jisoldi** [mulesoft-labs/raml-suggestions#13]
When there is an example node, inside of a type or a response, the following line does not have any suggestions, but it should. In the case that the caret in two lines below the example it works fine.
This is the case that doesn't work:
![screen shot 2016-10-06 at 5 57 32 pm](https://cloud.githubusercontent.com/assets/5315281/19170367/7dea96da-8bee-11e6-9c1f-885f44e11114.png)

This are the suggestions it should provide:
![screen shot 2016-10-06 at 5 57 55 pm](https://cloud.githubusercontent.com/assets/5315281/19170374/82e1d194-8bee-11e6-9a76-dd96c76bcaea.png)

**Comment by ddenisenko** [comment]
Reproducible, thank you.

**Comment by ddenisenko** [comment]
Copied to https://github.com/mulesoft/api-workbench/issues/327

**Comment by dreamflyer** [comment]
will be published in v0.0.21.

**Comment by jisoldi** [comment]
The same happens when there is an example in a resource, but this case was not fixed in the v0.0.21
This is the case that doesn't work:
<img width="368" alt="screen shot 2016-10-14 at 4 31 20 pm" src="https://cloud.githubusercontent.com/assets/5315281/19400264/c89ce708-922b-11e6-93f6-4eac952ad1b9.png">

This are the suggestions it should provide:
<img width="347" alt="screen shot 2016-10-14 at 4 31 31 pm" src="https://cloud.githubusercontent.com/assets/5315281/19400270/d0e5676e-922b-11e6-8314-68b6e0bb1a8e.png">

**Comment by ddenisenko** [comment]
Can not reproduce the last case. Could you please attach RAML file?

**Comment by jisoldi** [comment]
[LibraryExample.zip](https://github.com/mulesoft/raml-suggestions/files/530359/LibraryExample.zip)

The problem occurs in the slack.raml file.

**Comment by ddenisenko** [comment]
Thank you. Still not reproducible. Here is the snippet, directly invoking raml-suggestions for your example:
[exampletest.zip](https://github.com/mulesoft/raml-suggestions/files/533625/exampletest.zip)

To run:
1. unzip
2. `npm install`
3. `npm run run`
