### ISSUE TITLE
Inherited field from types defined in fragments are not suggested

### ISSUE THREAD

**Issue by nmarinel01** [mulesoft-labs/raml-suggestions#18]
Having the following raml fragment and raml specification:

*DataTypeA.raml*
```#%RAML 1.0 DataType
type: object
properties:
  name:
    required: true
    type: string
  age:
    required: false
    type: number
  /^note\d+$/: # restrict any properties whose keys start with "note"
                # followed by a string of one or more digits
    type: string
```
Then created another raml fragment named DataTypeB.raml
*DataTypeB.raml*
```#%RAML 1.0 DataType
type: !include dataTypeA.raml
properties: 
  employeeNo: string
```

Then, create an api that includes dataTypeB for a response type e.g.:
```
/resource:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: !include dataTypeB.raml
            example:
              employeeNo: 2oo
````
When we invoke suggestions under example node, it does not include name, nor age properties, the only suggestion is employeeNo. Nevertheless the parser validates missing name property since it has been defined as required

**Comment by dreamflyer** [comment]
will be published in v0.0.36.
