### ISSUE TITLE
Improvement: insertText for directories should include a slash `/` at the end

### ISSUE THREAD

**Issue by agustinlg** [mulesoft-labs/raml-suggestions#21]
When autocompleting a path for an include, it would be good that since you are always targeting files it automatically added the last slash to the insetText.
For instance:
- Having this file`directory/file.raml`
- And asking for suggestions in: `!include `
- Will return insertText: `directory/` instead of just `directory`
- End result will be: `!include directory/`, so asking for suggestions again will return `file.raml`, making it faster to complete a path.

**Comment by ddenisenko** [comment]
Sounds reasonable. @dreamflyer .

**Comment by dreamflyer** [comment]
will be published in v0.0.37.
