### ISSUE TITLE
Suggestions after certain code are not correct

### ISSUE THREAD

**Issue by jisoldi** [mulesoft-labs/raml-suggestions#24]
In the following example:
```
#%RAML 1.0
title: testShelf

/resourceName:
  #Point 4
  get:
    #POINT 1
    responses: 
      200:
        body: 
          application/json:
            type: string 
        headers:
          Content-Encoding:
            type: object
    #POINT 2
    #POINT 3
  #POINT 5
  #POINT 6
```
When situated at #Point 1 suggestions displayed in the shelf panel are not the same as those when situated at #Point 2, despite being at the same level.

However, when situated at #Point 3, suggestions are correctly displayed as in# Point 1.

This issue also occurs at "get" level with #Point 4, 5 and 6.

**Comment by dreamflyer** [comment]
will be published in v0.0.37.
